language: node_js
dist: xenial

services:
  - postgresql

node_js:
  - "4.1"
  - "6"
  - "8"
  - "10"
  - "11"
  - "12"
env:
  - CC=clang CXX=clang++ npm_config_clang=1 PGUSER=postgres PGDATABASE=postgres
  - PGUSER=postgres PGDATABASE=postgres PGSSLMODE=disable

addons:
  apt:
    packages:
      - openssl
      - libpq-dev
