language: node_js
dist: xenial

services:
  - postgresql

node_js:
  - "8"
  - "10"
  - "11"
  - "12"
env:
  - CC=clang CXX=clang++ npm_config_clang=1 PGUSER=postgres PGDATABASE=postgres
  - PGUSER=postgres PGDATABASE=postgres PGSSLMODE=disable

script:
  - ./install_openssl.sh 1.1.1
  - ./install_libpq.sh
  - export PATH=./vendor/postgres-11.3/bin/:$PATH
  - node -p process.versions
  - readelf -d build/Release/addon.node || true
  - npm test
