language: node_js
dist: xenial

services:
  - postgresql

node_js:
  - "8"
  - "10"
  - "11"
  - "12"
env:
  - CC=clang CXX=clang++ npm_config_clang=1 PGUSER=postgres PGDATABASE=postgres
  - PGUSER=postgres PGDATABASE=postgres PGSSLMODE=disable

script:
  - pg_config
  - ./install_openssl.sh 1.1.1
  - export PATH="./vendor/openssl-1.1.1/bin:${PATH}"
  - export CFLAGS="-I./vendor/openssl-1.1.1/include"
  - export LDFLAGS="-L./vendor/openssl-1.1.1/lib"
  - export LD_LIBRARY_PATH="./vendor/openssl-1.1.1/lib:$LD_LIBRARY_PATH"
  - export PKG_CONFIG_PATH="./vendor/openssl-1.1.1/lib/pkgconfig:$PKG_CONFIG_PATH"
  - ./install_libpq.sh
  - export PATH="./vendor/openssl-1.1.1/bin:./vendor/postgres-11.3/bin:${PATH}"
  - export CFLAGS="-I./vendor/openssl-1.1.1/include -I./vendor/postgres-11.3/include"
  - export LDFLAGS="-L./vendor/openssl-1.1.1/lib -L./vendor/postgres-11.3/lib"
  - export LD_LIBRARY_PATH="./vendor/openssl-1.1.1/lib:./vendor/postgres-11.3/lib:$LD_LIBRARY_PATH"
  - export PKG_CONFIG_PATH="./vendor/openssl-1.1.1/lib/pkgconfig:./vendor/postgres-11.3/lib/pkgconfig:$PKG_CONFIG_PATH"
  - node -p process.versions
  - npm rebuild
  - readelf -d build/Release/addon.node || true
  - readelf -d vendor/postgres-11.3/lib/libpq.so.5 || true
  - env
  - npm test
