language: node_js
dist: xenial

services:
  - postgresql

node_js:
  - "4.1"
  - "6"
  - "8"
  - "10"
  - "11"
  - "12"
env:
  - CC=clang CXX=clang++ npm_config_clang=1 PGUSER=postgres PGDATABASE=postgres
  - PGUSER=postgres PGDATABASE=postgres PGSSLMODE=disable

script:
  - node -p process.versions
  - node -p 'require("./build/Release/addon.node"); require("https").get("https://google.com/", res => { res.on("data", (d) => {console.log(d) }) })'
  - readelf -d /usr/lib/x86_64-linux-gnu/libpq.so.5 || true
  - npm test
